### PR TITLE
DXCDT-583: Convert scopes into a drop down in interactive mode in test token cmd

### PR DESCRIPTION
**Pull request by sergiught**
### 🔧 Changes

This PR converts the scopes flag into a multi selector picker when in interactive mode for the `auth0 test token` command.

### 📝 Checklist

- [x] All new/changed/fixed functionality is covered by tests (or N/A)
- [x] I have added documentation for all new/changed functionality (or N/A)

### CODE REVIEW

**Review by Widcket — APPROVED** [review]

**Comment by Widcket** [comment]
Should we print a warning when the app is M2M and scopes were passed?

**Comment by willvedd** [comment]
> Should we print a warning when the app is M2M and scopes were passed?

Maybe? It may be worth educating users of that misuse but there will be no ill consequences if they do include them.

**Comment by Widcket** [comment]
Should it be an "info" instead of a "warning" then?

**Comment by Widcket** [comment]
As a user, if a pass a combination of inputs expecting a certain result, I expect the app to let me know if this result cannot be achieved.

**Comment by Widcket** [comment]
It is a form of invalid input, after all. I wonder if there should be a flag validation rule for this, instead of a printed 'info'.

**Review by willvedd — APPROVED** [review]
Pulled and confirm that this works as intended.

**Review by Widcket — APPROVED** [review]

**Pull request merged**
