### PR TITLE
Remove actions commands [CLI-75]

### PR DESCRIPTION
**Pull request by Widcket**
### Description

This PR removes the actions commands, as the feature is no GA yet, and therefore subject to important changes.

### Testing

- [ ] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [X] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not `master`

### CODE REVIEW

**Review by cyx — APPROVED** [review]
Nice and clean! Any docs lying around?

**Comment by Widcket** [comment]
> Nice and clean! Any docs lying around?

There were mocks, scopes, and logs-related logic remaining 🙈.
There are some files that can't be removed yet, as the rate-limit related logic is used by `logs`:

Screen Shot 2021-03-19 at 15 24 00

Screen Shot 2021-03-19 at 15 18 35

These files are the following:
- https://github.com/auth0/auth0-cli/blob/main/internal/auth0/actions.go
- https://github.com/auth0/auth0-cli/blob/main/internal/auth0/actions/actions.go

**Review by jfatta — APPROVED** [review]
🧼 👍

**Comment by cyx** [comment]
Oh yeah, good that you uncovered these skeletons. _I think_ we can keep that part of actions since I don't think the API call to fetch an execution will change. 👍

**Pull request merged**
