### PR TITLE
Add branding texts commands

### PR DESCRIPTION
**Pull request by Widcket**
### Description

This PR adds the following commands:

- `auth0 branding texts show`: Shows the custom texts for a prompt.
- `auth0 branding texts update`: Updates the custom texts for a prompt.

#### With default lang

https://user-images.githubusercontent.com/5055789/139497521-fcdeb7cd-a2ae-4063-a531-f988dab2e745.mov

#### With custom lang

https://user-images.githubusercontent.com/5055789/139497604-fbb30248-6aa9-4bd3-b1ca-9634d929d678.mov

#### Piping the input

Screen Shot 2021-10-29 at 17 15 38

### References

https://auth0.com/docs/brand-and-customize/text-customization-new-universal-login

### Testing

This change was tested manually, **with every prompt there is**, according to the docs.

- [ ] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not `master`

### CODE REVIEW

**Review by jfatta — APPROVED** [review]
looks good 👏🏼 
could you add `branding` unit tests?

**Comment by sergiughf** [comment]
Apologies if this is a silly question, but what is forcing us to include the vendor folder into the project?

**Comment by cyx** [comment]
Probably the strongest reason is convention. Vendor if if it's not a library.

**Comment by Widcket** [comment]
> could you add branding unit tests?

Just added a couple.

**Pull request merged**
